#####################################################################
### default: settings section for (ANY environment).              ###
### Note: this attributes can be overwrited by any other sections ###
#####################################################################
[default]
settings_scope = "default"

[default.api]
url_prefix = "/api/v1"

[default.security]
# Set api key in .secrets.toml or in environment variable
# APILAYER_API_KEY = ""
# ETH_API_KEY = ""

########################################################################
### development: settings section just for DEVELOPMENT environment.  ###
########################################################################
[development]
settings_scope = 'development'